version: '3.8'

services:
  flight_static:
    image: nginx:alpine
    container_name: flight_static
    restart: unless-stopped
    volumes:
      - ./build:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=wegofare.com
      - LETSENCRYPT_HOST=wegofare.com
      - VIRTUAL_PORT=80
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external:
      name: farebulkseo_default
